### ISSUE TITLE
Rendering shaft using instancing or batching is not working

### ISSUE THREAD

**Issue by SrRapero720** [txnimc/BalancedFlight#10]
Restarting game fix it, but leaving worlds causes the issue
MC: 1.18.2
FG: 40.2.9
MOD: balancedflight-1.18.2_v2.1.0.jar

## VIDEO
https://github.com/anthxnymc/BalancedFlight/assets/29090346/4a8e31c1-00fc-45ab-af30-89dedb5fc1b2

**Comment by 123ghaksd** [comment]
same in 1.19.2 v2.1.0
