### ISSUE TITLE
Permanent Slow Fall Bug (1.20.1)

### ISSUE THREAD

**Issue by IulianDan** [txnimc/BalancedFlight#16]
I installed this mod on a server I made for a custom pack to play with friends and I noticed this mod gives you slow falling whenever you enter Spectator Mode. Well, yesterday I crashed while having that effect and it's now constantly refreshing and no matter what I do (respawning, deleting player data, restarting the server, clearing it with commands, clearing it with milk) I can't get rid of it. It keeps refreshing it's duration to 10, like it's being constantly applied to me. My friends do not have this issue.
I know it's this mod because removing it got rid of the effect. Also, adding it back did not solve it, I still have the incurable effect
-- Versions & stuff --
Minecraft Version: 1.20.1
Forge Version: 47.1.42
Mod Version 2.1.0

**Comment by SrRapero720** [comment]
have you ars noevau??

**Comment by MoonMoonShark** [comment]
i'm also having this problem on a 1.19.2 server with a custom modpack. (no ars nouvea)

-- Versions & stuff --
Minecraft Version: 1.19.2
Forge Version: 43.2.23
Mod Version 2.1.0

for testing, i made the most minimal of packs, with only the required mods, and i still got the slow falling effect as soon as i went into spectator mode.

- geckolib-forge-1.19-3.1.40
- curios-forge-1.19.2-5.1.4.1
- create-1.19.2-0.5.1.c
- balancedflight-1.19.2_v2.1.0

**Comment by MoonMoonShark** [comment]
i'll spend some time tonight going through my modpack to see if i can figure out what it's conflicting with.

**Comment by MoonMoonShark** [comment]
i just made the most minimal of packs, and i still got the slow falling effect as soon as i went into spectator mode.

- geckolib-forge-1.19-3.1.40
- curios-forge-1.19.2-5.1.4.1
- create-1.19.2-0.5.1.c
- balancedflight-1.19.2_v2.1.0

**Comment by Boastful1353** [comment]
FTB Unstable 1.20.1 here. Same issue.

**Comment by Looxond** [comment]
Same issue here

**Comment by MoonMoonShark** [comment]
i was hoping that maybe now that create is on v0.5.1f instead of c, maybe this problem would be miraculously fixed, so i tried installing it again. i spent a whole day flying around with the beacon running, working on other stuff, and no slow fall! i was so excited and thought that was it! then i removed the beacon and immediately got slow fall again. nothing i could do would make it go away. so, sadly, it's still broken. :(
