### ISSUE TITLE
1.20.1 not loading properly

### ISSUE THREAD

**Issue by DadudeGaming** [txnimc/BalancedFlight#25]
Crash report
[crash-2023-10-18_16.22.17-fml.txt](https://github.com/anthxnymc/BalancedFlight/files/13033659/crash-2023-10-18_16.22.17-fml.txt)
Modlist:
Create
Balanced flight
Curios Api
Gecko lib
Using forge 47.2.1

**Comment by DadudeGaming** [comment]
also getting this
![image](https://github.com/anthxnymc/BalancedFlight/assets/76189578/837daebf-ce54-42cf-8bab-98fcb6a46154)

**Comment by DadudeGaming** [comment]
Just found this
<img width="458" alt="image" src="https://github.com/anthxnymc/BalancedFlight/assets/76189578/b5cc2d1f-1419-414d-beaf-c7c698079c25">

**Comment by mcdodge34** [comment]
Same problem, so subscribing to get updated when this get fixed.

**Comment by Gohirro** [comment]
Same issue here. Forge 47.2.0. Tried all the avail releases for 1.20.1 and gets the same MAIN TAB error.
