### ISSUE TITLE
java.lang.NoSuchFieldError: MAIN_TAB

### ISSUE THREAD

**Issue by localsol** [txnimc/BalancedFlight#27]
So i get this error when iI try to start minecraft
heres the crash log:
[crash-2023-11-27_11.09.53-fml.txt](https://github.com/anthxnymc/BalancedFlight/files/13472310/crash-2023-11-27_11.09.53-fml.txt)
The mods I have downloaded are:
FarmersDelight-1.20.1-1.2.3.jar
geckolib-forge-1.20.1-4.2.4.jar
jei-1.20.1-forge-15.2.0.27.jar
garnished-1.2-hotfix-2+1.20.1.jar
sophisticatedcore-1.20.1-0.5.83.395.jar
curios-forge-5.4.2+1.20.1.jar
create-1.20.1-0.5.1.e.jar
Xaeros_Minimap_23.6.3_Forge_1.20.jar
balancedflight-1.20.1_v2.1.0.jar
storagedrawers-1.20.1-12.0.2.jar
entityculling-forge-1.6.2-mc1.20.jar
canary-mc1.20.1-0.2.7.jar
sophisticatedbackpacks-1.20.1-3.18.56.890.jar
createdieselgenerators-1.20.1-1.2d.jar
ferritecore-6.0.0-forge.jar
cc-tweaked-1.20.1-forge-1.107.0.jar
createaddition-1.20.1-1.1.1.jar

![image](https://github.com/anthxnymc/BalancedFlight/assets/152163334/b616a0c8-537c-419c-8fa9-6b8017cdc8a8)

**Comment by s1avko** [comment]
hi, current workaround for this problem is to downgrade the create mod to 0.5.1d, at least thats what I managed to figure out

**Comment by katubug** [comment]
Same issue here.
