### ISSUE TITLE
 BalancedFlight breaks all other mods that add any form of creative flight

### ISSUE THREAD

**Issue by IBims1NicerTobi** [txnimc/BalancedFlight#32]
Any mod that allows you to fly is broken when installing this mod

**Comment by sprocketaudio** [comment]
Yes please fix this is really annoying! It jsut gives you feather falling forever.

Examples - Orb of temporary flight from Forbidden Arcanus
Infinity chestplate from Re-Aviritia

1.19.2

**Comment by tlitookilakin** [comment]
This issue is also present in 1.20.1. It even disables actual legit creative mode flight.

**Comment by arketec** [comment]
1.20.1 confirmed. It seems to mess up something in the save data as well. When using Apotheosis Potions of Flying it breaks them bad and doubles the time of effect every time it's used. This issue persists after BalancedFlight is uninstalled as well, but only occurs when BalancedFlight is added. I was forced to load a backup to solve the issue.

**Comment by Rahmiel** [comment]
With this level of issue and the fact that it isn't being fixed, this mod needs to be reported on Curse. Do your due diligence to prevent mod authors like this one from doing what they do.

**Comment by txnitxnichopper** [comment]
you can't report mods for having a bug 💀 

it's open source nothing is stopping you from making whatever changes you want

**Comment by tlitookilakin** [comment]
I see that this is closed as completed but with no recent commits, apparently alongside a bunch of other open issues. Are you abandoning the mod or did you just forget to push your changes? If the former, please mark this repository as an archive.

**Comment by sprocketaudio** [comment]
> I see that this is closed as completed but with no recent commits, apparently alongside a bunch of other open issues. Are you abandoning the mod or did you just forget to push your changes? If the former, please mark this repository as an archive.

Looks like balancedflight-1.20.1_v2.3.0.jar fixes this according to the patch notes on curseforge.

_Fix slow fall issue Add compat with Valkrien Skies_

**Comment by Legende04** [comment]
how I see that the craetive flight, offered by gobber mods dragon armor does not work.
I guess its balanced flight again...

would be awesome if this got fixed, or like a config option to enable flight, by other mods...
