### ISSUE TITLE
Incompatibility with FTB Essentials 1.20.1, permanent slowfalling with any form of flight outside of creative mode/switching gamemodes

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [txnimc/BalancedFlight#33]
I've been struggling with finding the reason for the permanent slow falling with using /fly on singleplayer/multiplayer while testing a new modpack, and I'm here to report an incompatibility. Going into creative mode, out of /fly or having the flight effect expire allows the slowfalling effect to tick down and disappear. But **ANY** flight-related mechanic in survival otherwise leaves this effect. 

Forge 47.2.30
Create 0.5.1f
Create Balanced Flight 2.2.0
Curios 5.9.1
FTB library 2001.2.2
FTB essentials 2001.2.2
FTB ranks 2001.1.3 

https://github.com/anthxnymc/BalancedFlight/issues/32
https://github.com/anthxnymc/BalancedFlight/issues/31
https://github.com/anthxnymc/BalancedFlight/issues/16
https://github.com/anthxnymc/BalancedFlight/issues/11

**Comment by Looxond** [comment]
Can confirm

**Comment by xRiis** [comment]
Slow-falling effect is also applied on world generation if you spawn in creative mode and will not disappear unless you die
