### ISSUE TITLE
Dedicated server crash on startup

### ISSUE THREAD

**Issue by Vllaaad** [txnimc/BalancedFlight#9]
My mod pack has 150+mods. Balanced flight works perfectly in client-side but when I launch a dedicated server it crashes with the following error:

[latest.log](https://github.com/anthxnymc/BalancedFlight/files/11951217/latest.log)

**Comment by txnitxnichopper** [comment]
will fix

**Comment by txnitxnichopper** [comment]
should be fixed in latest release, might take a sec for Curseforge to approve.
